#ifndef HDEF_TEXTUREFACTORY
#define HDEF_TEXTUREFACTORY

#include <memory>
#include <unordered_map>
#include <string>

#include "../AbstractTextureFactory.h"

#include "SDL3/SDL.h"

// struct SDL_Renderer;
namespace Mochi::FS
{
    class PackCatalog;
}
namespace Mochi::Graphics
{
    class SDLRenderer;
    /**
     * @brief This implementation of AbstractTextureFactory just loads textures using the SDL_Renderer provided in the constructor.
     *
     * It doesn't load textures directly from the drive, but uses the catalog file system to load the binary data of textures
     * and create them with IMG_LoadTexture_IO.
     *
     * Ownership:
     *
     * - It has the same ownership as AbstractTextureFactory, which is a cache of textures generated by itself.
     *
     * - It has a pointer to the SDL_Renderer, but doesn't own it.
     */
    class SDLTextureFactory : public AbstractTextureFactory
    {
    private:
        friend class SDLRenderer;
        SDLTextureFactory(FS::PackCatalog *catalog, SDL_Renderer *renderer);
        FS::PackCatalog *mCatalog;
        SDL_Renderer *mRenderer;

    protected:
        virtual std::shared_ptr<ITexture> LoadTexture(const std::string &texturePath) override;

    public:
        virtual ~SDLTextureFactory();
    };
}

#endif