#ifndef HDEF_FMODWRAPPER
#define HDEF_FMODWRAPPER

#include "IAudioManager.h"

#include <fmod_common.h>
#include <fmod_studio_common.h>
#include <vector>
#include <string>
#include <memory>
#include <unordered_map>
#include <sol/sol.hpp>

struct FMOD_STUDIO_SYSTEM;
struct FMOD_STUDIO_BANK;
struct FMOD_STUDIO_EVENTDESCRIPTION;
struct FMOD_STUDIO_EVENTINSTANCE;

namespace Mochi::FS
{
    class PackCatalog;
}
namespace Mochi::Scripting
{
    class ScriptingManager;
}
namespace Mochi::Audio
{
    struct FMODMarkerEvent
    {
        const char *MarkerName;
        int MarkerPosition;
    };
    /**
     * @brief Implementation of IAudioManager wrapping the C API of FMOD and FMOD Studio.
     * FMOD uses audio banks generated with FMOD Studio instead of plain audio files.
     *
     * This class also stablishes a callback to be called whenever a BGM event reaches a timeline marker, useful for coordinating
     * game events with the music.
     *
     * Guarantees:
     *
     * - Loaded audio banks can have their events played.
     *
     * - Audio banks are loaded for as long as the FMODWrapper object is not destroyed and the banks are not unloaded.
     *
     * - Audio parameters from FMOD studio can be changed.
     *
     * - Volume can be changed on a per bus basis.
     *
     * - A callback is dispatched in the LUA environment whenever the BGM reaches a timeline marker. They are put in a queue and called safely in the main thread.
     *
     * - All FMOD elements are correctly released when the FMODWrapper object is destroyed.
     *
     * Non-responsible:
     *
     * - Audio banks are not automatically loaded in any way. LoadAudio has to be called for them to be loaded.
     *
     * Thread safety:
     *
     * - FMOD is run in a separate thread.
     *
     * - Update can not be called in a separate thread because it interacts with the scripting system.
     */
    class FMODWrapper : public IAudioManager
    {
    private:
        struct FMOD_Bank_Pair
        {
            FMOD_STUDIO_BANK *bank;
            FMOD_STUDIO_BANK *stringsBank;
        };

        FMOD_STUDIO_SYSTEM *mFmodSystem;
        FMOD_STUDIO_EVENTDESCRIPTION *mBgmEventDescription;
        FMOD_STUDIO_EVENTINSTANCE *mBgmEventInstance;
        std::vector<FMOD_Bank_Pair> mBankPairs;
        std::unordered_map<std::string, FMOD_Bank_Pair> mBankPairsMap;
        static FMOD_RESULT F_CALL EventCallback(FMOD_STUDIO_EVENT_CALLBACK_TYPE type, FMOD_STUDIO_EVENTINSTANCE *event, void *parameters);
        void OnEventCallback(FMOD_STUDIO_EVENT_CALLBACK_TYPE type, FMOD_STUDIO_EVENTINSTANCE *event, void *parameters);
        FS::PackCatalog *mCatalog;
        Scripting::ScriptingManager *mScripting;
        std::unordered_map<std::string, FMOD_STUDIO_EVENTDESCRIPTION *> mSoundCache;
        std::unordered_map<std::string, FMOD_STUDIO_BUS *> mBusesCache;

        void LoadBank(const std::string &bankName);
        void UnloadBank(const std::string &bankName);
        void SetBusVolume(const std::string &busGroupName, const float &value);

        std::vector<FMODMarkerEvent> mEventQueue;

    public:
        /// @brief
        /// @param catalog The file system catalog to load the audio banks from.
        /// @param scriptingManager The scripting manager module, used specifically by this class to dispatch timeline marker events.
        FMODWrapper(FS::PackCatalog *catalog, Scripting::ScriptingManager *scriptingManager);
        virtual ~FMODWrapper();
        /// @brief Updates the FMOD system and dispatches safely the timeline marker events.
        /// @param dt Delta time
        virtual void Update(const float &dt) override;
        /// @brief Loads the .bank and .strings.bank files generated by FMOD Studio.
        /// @param path The path or unique identifier of the bank in the catalog, without extension (so master will search for Master.bank and Master.strings.bank)
        virtual void LoadAudio(const std::string &path) override { LoadBank(path); }
        /// @brief Unloads a loaded audio bank. If the audio bank didn't exist or wasn't loaded, it does nothing. This also clears the cached buses
        /// with SetMixerVolume/SetBusVolume, as they depend on the bank.
        /// @param path The path or unique identifier of the bank, without extension.
        virtual void UnloadAudio(const std::string &path) override { UnloadBank(path); };
        /// @brief Plays an FMOD event after stopping (if applicable) previous started BGMs.
        /// @param eventName Name of the event in FMOD Studio.
        virtual void PlayBGM(const std::string &eventName) override;
        /// @brief Pauses current BGM without changing the timeline position.
        virtual void PauseBGM() override;
        /// @brief Resumes the BGM on the previous timeline position.
        virtual void ResumeBGM() override;
        /// @brief Stops the BGM, essentially resetting its state.
        virtual void StopBGM() override;
        /// @brief If playing a BGM, moves the timeline position of the song to the specified point in time.
        /// @param ms Time in milliseconds to which move on the song.
        virtual void SkipToTimelinePosition(const int &ms) override;
        /// @brief Plays an audio event without need to stop previous audio events. This is meant to play short SFX.
        /// When an audio is played this way, its data is cached to be played again later.
        /// @param eventName Name of the event in FMOD Studio.
        virtual void PlayOneShot(const std::string &eventName) override;
        /// @brief Clears the cache generated when playing sounds with PlayOneShot.
        void ClearSoundCache() { mSoundCache.clear(); }
        /// @brief Clears the cache generated when setting the volume.
        void ClearBusCache() { mBusesCache.clear(); }
        /// @brief Sets a parameter that is used in FMOD Studio for different purposes, like blending musics or applying filters.
        /// This requires a bank to be loaded.
        /// @param parameterName The name of the parameter in FMOD Studio.
        /// @param value The value of the parameter.
        virtual void SetParameter(const std::string &parameterName, const float &value) override;
        /// @brief Sets the volume in an audio bus. This requires a bank to be loaded.
        /// @param busGroupName The name of the bus group in FMOD Studio. Use an empty string for the master bus.
        /// @param value A value between 0f and 1f.
        virtual void SetMixerVolume(const std::string &busGroupName, const float &value) override { SetBusVolume(busGroupName, value); };
    };
}

#endif