#ifndef HDEF_SCRIPTINGLAYER
#define HDEF_SCRIPTINGLAYER

#include <memory>
#include <vector>

#include "../Layer.h"

namespace Mochi::Graphics
{
    class SpriteBase;
    class AbstractTextureFactory;
    class IAnimationFactory;
}
namespace Mochi::Scripting
{
    /**
     * @brief This layer is automatically injected in the engine in the setup phase and is designed to bind several useful methods to the lua environment
     * and take ownership of entities generated by lua.
     *
     * Check @ref LuaBindings for a description of submodule bindings.
     *
     * Ownership:
     *
     * - Owner of graphical entities (SpriteBase) generated from lua scripts.
     *
     * - Has its own texture factory and animation factory to have its own cache.
     *
     *
     * Guarantees:
     *
     * - When doing the engine setup, the most common engine methods will be automatically binded in the lua global table.
     *
     * - This layer is automatically injected in the engine as the engine setups.
     *
     * - Sprites destroyed from lua will be safely destroyed in C++ on each frame.
     *
     * - Sprites created from lua will be updated (for animations) and rendered each frame.
     *
     *
     * Non responsible:
     *
     * - This class does not auto-load any user created lua script.
     *
     * - If manually injecting entities on the lua state, this class does not manage their lifetime nor has their ownership.
     */
    class ScriptingLayer : public Layer
    {
    private:
        std::unique_ptr<Graphics::AbstractTextureFactory> mTextureFactory;
        std::unique_ptr<Graphics::IAnimationFactory> mAnimationFactory;
        std::vector<std::shared_ptr<Graphics::SpriteBase>> mSprites;
        std::vector<std::shared_ptr<Graphics::SpriteBase>> mSpritesToDestroy;
        /// @brief Binds creation of shared pointers for sprites and their children classes to lua.
        void BindFactoryMethods();

    public:
        ScriptingLayer();
        virtual ~ScriptingLayer();
        /// @brief Calls BindFactoryMethods and graphics, logic and audio bindings to lua.
        ///
        /// Check @ref LuaBindings for a description of submodule bindings.
        virtual void InitLayer() override;
        /// @brief Updates owned sprites (for animations) and safely removes sprites marked for destruction.
        /// @param dt Delta time
        /// @return Always true (continue game execution)
        virtual bool Update(const float &dt) override;
        /// @brief Renders owned sprites.
        virtual void Render() const override;
        /// @brief This class does not show any GUI.
        virtual void GUI() override;
#if DEBUG
        /// @brief This class does not show any debug data.
        virtual void Debug() const override;
#endif
    };
}

#endif