.TH "Mochi::Graphics::SDLGUI" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::SDLGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::AbstractGUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBGUIResult\fP \fBSprite\fP (const \fBGUIOptions\fP &options) override"
.br
.ti -1c
.RI "virtual \fBGUIResultButton\fP \fBButton\fP (const \fBGUIButtonOptions\fP &options, const char *label, const \fBGUITextOptions\fP &textOptions) override"
.br
.ti -1c
.RI "virtual \fBGUIResult\fP \fBText\fP (const char *label, const \fBGUITextOptions\fP &options) override"
.br
.in -1c

Public Member Functions inherited from \fBMochi::Graphics::AbstractGUI\fP
.in +1c
.ti -1c
.RI "\fBAbstractGUI\fP (\fBFS::PackCatalog\fP *catalog, \fBIRenderer\fP *renderer, \fBInput::IActionManager\fP *actionManager)"
.br
.ti -1c
.RI "void \fBUpdate\fP (const float &dt)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSDLRenderer\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMochi::Graphics::AbstractGUI\fP
.in +1c
.ti -1c
.RI "GUIElementId \fBGetNextId\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdate\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBMochi::Graphics::AbstractGUI\fP
.in +1c
.ti -1c
.RI "GUIElementId \fBmFocusId\fP"
.br
.ti -1c
.RI "GUIElementId \fBmPressedId\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBAbstractTextureFactory\fP > \fBmTextureFactory\fP"
.br
.ti -1c
.RI "\fBIRenderer\fP * \fBmRenderer\fP"
.br
.ti -1c
.RI "\fBFS::PackCatalog\fP * \fBmCatalog\fP"
.br
.ti -1c
.RI "\fBInput::IActionManager\fP * \fBmActionManager\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBGUIResultButton\fP Mochi::Graphics::SDLGUI::Button (const \fBGUIButtonOptions\fP & options, const char * label, const \fBGUITextOptions\fP & textOptions)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBMochi::Graphics::AbstractGUI\fP\&.
.SS "\fBGUIResult\fP Mochi::Graphics::SDLGUI::Sprite (const \fBGUIOptions\fP & options)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBMochi::Graphics::AbstractGUI\fP\&.
.SS "\fBGUIResult\fP Mochi::Graphics::SDLGUI::Text (const char * label, const \fBGUITextOptions\fP & options)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBMochi::Graphics::AbstractGUI\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
