.TH "Mochi::Graphics::GUIButtonOptions" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::GUIButtonOptions
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGUIOptions\fP \fBBaseOptions\fP"
.br
.ti -1c
.RI "\fBGUIOptions\fP \fBFocusedOptions\fP"
.br
.ti -1c
.RI "\fBGUIOptions\fP \fBPressedOptions\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
