.TH "Mochi::Input::PerformableActionMouse" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::PerformableActionMouse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IPerformableAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerformableActionMouse\fP (const nlohmann::json &json)"
.br
.ti -1c
.RI "virtual bool \fBIsPerformed\fP (\fBInputManager\fP *input) const"
.br
.ti -1c
.RI "virtual float \fBGetValue\fP (\fBInputManager\fP *input) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float Mochi::Input::PerformableActionMouse::GetValue (\fBInputManager\fP * input) const\fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IPerformableAction\fP\&.
.SS "bool Mochi::Input::PerformableActionMouse::IsPerformed (\fBInputManager\fP * input) const\fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IPerformableAction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
