.TH "Mochi::FS::FileEntry" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::FS::FileEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "FileOffset_t \fBoffset\fP"
.br
.ti -1c
.RI "FileSize_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
