.TH "Mochi::ActionManagerSwappedEvent" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::ActionManagerSwappedEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInput::IActionManager\fP * \fBnewActionManager\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
