.TH "Mochi::Input::IMouseProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::IMouseProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Input::DummyMouseProvider\fP, and \fBMochi::Input::SDLMouseProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::array< bool, MouseButton::MouseButtonsCount > \fBGetState\fP (float *x, float *y) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
