.TH "Mochi::Event::DummyEventDispatcher" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Event::DummyEventDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Event::ISystemEventDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPollEvents\fP () const override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Mochi::Event::DummyEventDispatcher::PollEvents () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Event::ISystemEventDispatcher\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
