.TH "Mochi::RendererSwappedEvent" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::RendererSwappedEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphics::IRenderer\fP * \fBnewRenderer\fP"
.br
.ti -1c
.RI "\fBGraphics::AbstractGUI\fP * \fBnewGui\fP"
.br
.ti -1c
.RI "\fBDebug::IGizmos\fP * \fBnewGizmos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
