.TH "Mochi::Input::VirtualActionManager" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::VirtualActionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IActionManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBLoadActions\fP (std::vector< char > buffer) override"
.br
.ti -1c
.RI "virtual bool \fBLoadActionsFromFile\fP (const std::string &path) override"
.br
.ti -1c
.RI "virtual bool \fBHasAction\fP (const std::string &) const override"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (const float &dt) override"
.br
.ti -1c
.RI "virtual bool \fBPerformed\fP (const std::string &actionName) const override"
.br
.ti -1c
.RI "virtual float \fBValue\fP (const std::string &actionName) const override"
.br
.ti -1c
.RI "virtual \fBVector2f\fP \fBCompoundValue\fP (const std::string &action1, const std::string &action2) const override"
.br
.ti -1c
.RI "void \fBSetActionState\fP (const std::string &action, const float &state)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBVector2f\fP Mochi::Input::VirtualActionManager::CompoundValue (const std::string & action1, const std::string & action2) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "bool Mochi::Input::VirtualActionManager::HasAction (const std::string & ) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "bool Mochi::Input::VirtualActionManager::LoadActions (std::vector< char > buffer)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "bool Mochi::Input::VirtualActionManager::LoadActionsFromFile (const std::string & path)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "bool Mochi::Input::VirtualActionManager::Performed (const std::string & actionName) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "void Mochi::Input::VirtualActionManager::Update (const float & dt)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.
.SS "float Mochi::Input::VirtualActionManager::Value (const std::string & actionName) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IActionManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
