.TH "Mochi::Input::IPerformableAction" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::IPerformableAction
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Input::PerformableActionGamepad\fP, \fBMochi::Input::PerformableActionGamepadAxis\fP, \fBMochi::Input::PerformableActionKeyboard\fP, \fBMochi::Input::PerformableActionMouse\fP, and \fBMochi::Input::PerformableActionMouseAxis\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBIsPerformed\fP (\fBInputManager\fP *input) const =0"
.br
.ti -1c
.RI "virtual float \fBGetValue\fP (\fBInputManager\fP *input) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
