.TH "Mochi::Input::IActionManager" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::IActionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Input::ActionManager\fP, and \fBMochi::Input::VirtualActionManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBLoadActions\fP (std::vector< char > buffer)=0"
.br
.ti -1c
.RI "virtual bool \fBLoadActionsFromFile\fP (const std::string &path)=0"
.br
.ti -1c
.RI "virtual bool \fBHasAction\fP (const std::string &) const =0"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (const float &dt)=0"
.br
.ti -1c
.RI "virtual bool \fBPerformed\fP (const std::string &actionName) const =0"
.br
.ti -1c
.RI "virtual float \fBValue\fP (const std::string &actionName) const =0"
.br
.ti -1c
.RI "virtual \fBVector2f\fP \fBCompoundValue\fP (const std::string &action1, const std::string &action2) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
