.TH "Mochi::FS::PackHeader" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::FS::PackHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PackHeaderLength_t \fBHeaderLength\fP"
.br
.ti -1c
.RI "size_t \fBBlobSize\fP"
.br
.ti -1c
.RI "Header_t \fBHeaderMap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
