.TH "Mochi::Time::Chrono" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Time::Chrono
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetTime\fP () const"
.br
.ti -1c
.RI "void \fBTick\fP (const float &dt)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
