.TH "Mochi::Input::DummyKeyboardProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::DummyKeyboardProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IKeyboardProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const bool * \fBGetState\fP () const override"
.br
.ti -1c
.RI "virtual size_t \fBGetMaxKeys\fP () const override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual size_t Mochi::Input::DummyKeyboardProvider::GetMaxKeys () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IKeyboardProvider\fP\&.
.SS "virtual const bool * Mochi::Input::DummyKeyboardProvider::GetState () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IKeyboardProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
