.TH "Mochi::Audio::IAudioManager" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Audio::IAudioManager
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Audio::DummyAudioManager\fP, and \fBMochi::Audio::FMODWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP (const float &dt)=0"
.br
.ti -1c
.RI "virtual void \fBLoadAudio\fP (const std::string &path)=0"
.br
.ti -1c
.RI "virtual void \fBUnloadAudio\fP (const std::string &path)=0"
.br
.ti -1c
.RI "virtual void \fBPlayBGM\fP (const std::string &audioName)=0"
.br
.ti -1c
.RI "virtual void \fBPauseBGM\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBStopBGM\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBResumeBGM\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSkipToTimelinePosition\fP (const int &ms)=0"
.br
.ti -1c
.RI "virtual void \fBPlayOneShot\fP (const std::string &audioName)=0"
.br
.ti -1c
.RI "virtual void \fBSetParameter\fP (const std::string &parameterName, const float &value)=0"
.br
.ti -1c
.RI "virtual void \fBSetMixerVolume\fP (const std::string &mixerGroupName, const float &value)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
