.TH "Mochi::Graphics::ITexture" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::ITexture \- A texture interface to be implemented by renderer specific textures\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ITexture\&.h>\fP
.PP
Inherited by \fBMochi::Graphics::DummyTexture\fP, and \fBMochi::Graphics::SDLTexture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBVector2f\fP \fBGetSize\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBSetAlpha\fP (const uint8_t &alpha)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A texture interface to be implemented by renderer specific textures\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
