.TH "Mochi::Event::EventBus" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Event::EventBus
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename EventType> SubscriptionHandler \fBSubscribe\fP (std::function< void(const EventType &)> callback)"
.br
.ti -1c
.RI "template<typename EventType> void \fBUnsubscribe\fP (SubscriptionHandler handler)"
.br
.ti -1c
.RI "template<typename EventType> void \fBPublish\fP (const EventType &event)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
