.TH "Mochi::Audio::FMODMarkerEvent" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Audio::FMODMarkerEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBMarkerName\fP"
.br
.ti -1c
.RI "int \fBMarkerPosition\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
