.TH "Mochi::FS::SystemFileLoader" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::FS::SystemFileLoader \- This class creates a very simple virtual file system from a directory\&. This allows read access to all files in that directory referencing them from their path as a unique identifier\&. As this doesn't give the benefits of asset obfuscation, it is only used on debug mode, and can't be configured at the moment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SystemFileLoader\&.h>\fP
.PP
Inherits \fBMochi::FS::IFileLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSystemFileLoader\fP (const std::string &directoryPath)"
.br
.ti -1c
.RI "virtual bool \fBIsValid\fP () const"
.br
.RI "Tells us if the file loader can be used at the moment\&. "
.ti -1c
.RI "virtual std::vector< char > \fBGetFile\fP (const std::string &path)"
.br
.RI "Give us a binary representation of a file in a filesystem\&. "
.ti -1c
.RI "virtual bool \fBHasFile\fP (const std::string &path) const"
.br
.RI "Tells us if the filesystem has a file\&. "
.ti -1c
.RI "virtual std::vector< std::string > \fBGetAvailableFiles\fP () const"
.br
.RI "Tells us which files are in the filesystem\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class creates a very simple virtual file system from a directory\&. This allows read access to all files in that directory referencing them from their path as a unique identifier\&. As this doesn't give the benefits of asset obfuscation, it is only used on debug mode, and can't be configured at the moment\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > Mochi::FS::SystemFileLoader::GetAvailableFiles () const\fR [virtual]\fP"

.PP
Tells us which files are in the filesystem\&. 
.PP
\fBReturns\fP
.RS 4
A vector with the unique identifiers of all files 
.RE
.PP

.PP
Implements \fBMochi::FS::IFileLoader\fP\&.
.SS "std::vector< char > Mochi::FS::SystemFileLoader::GetFile (const std::string & path)\fR [virtual]\fP"

.PP
Give us a binary representation of a file in a filesystem\&. 
.PP
\fBExceptions\fP
.RS 4
\fI\fBEngineError\fP\fP if is not valid or doesn't have file 
.RE
.PP
\fBParameters\fP
.RS 4
\fIpath\fP A path, or unique identifier to the file 
.RE
.PP
\fBReturns\fP
.RS 4
A vector of chars, or binary representation of a file\&. 
.RE
.PP

.PP
Implements \fBMochi::FS::IFileLoader\fP\&.
.SS "bool Mochi::FS::SystemFileLoader::HasFile (const std::string & path) const\fR [virtual]\fP"

.PP
Tells us if the filesystem has a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP A path, or unique identifier to the file 
.RE
.PP
\fBReturns\fP
.RS 4
True if it has the file, false if not 
.RE
.PP

.PP
Implements \fBMochi::FS::IFileLoader\fP\&.
.SS "bool Mochi::FS::SystemFileLoader::IsValid () const\fR [virtual]\fP"

.PP
Tells us if the file loader can be used at the moment\&. 
.PP
\fBReturns\fP
.RS 4
True if can be used, false if not 
.RE
.PP

.PP
Implements \fBMochi::FS::IFileLoader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
