.TH "Mochi::AudioOperationError" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::AudioOperationError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::EngineError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioOperationError\fP (const std::string &operation, const std::string &msg)"
.br
.in -1c

Public Member Functions inherited from \fBMochi::EngineError\fP
.in +1c
.ti -1c
.RI "\fBEngineError\fP (const std::string &msg, std::source_location loc=std::source_location::current())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
