.TH "Mochi::Vector2f" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Vector2f
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2f\fP (float _x=0, float _y=0)"
.br
.ti -1c
.RI "\fBVector2f\fP (const Vector2f &v)"
.br
.ti -1c
.RI "\fBVector2f\fP (Vector2f &&v)"
.br
.ti -1c
.RI "\fBVector2f\fP (const SDL_FPoint &p)"
.br
.ti -1c
.RI "\fBoperator SDL_FPoint\fP () const"
.br
.ti -1c
.RI "Vector2f & \fBoperator=\fP (const Vector2f &other)"
.br
.ti -1c
.RI "Vector2f & \fBoperator=\fP (const SDL_FPoint &other)"
.br
.ti -1c
.RI "Vector2f & \fBoperator+=\fP (const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f & \fBoperator\-=\fP (const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f & \fBoperator*=\fP (const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f & \fBoperator*=\fP (const float &rhs)"
.br
.ti -1c
.RI "Vector2f & \fBoperator/=\fP (const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f & \fBoperator/=\fP (const float &rhs)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const Vector2f &rhs)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "float \fBDistance\fP () const"
.br
.ti -1c
.RI "Vector2f \fBNormalized\fP () const"
.br
.RI "Returns a new copy of the vector, normlized\&. If vector was 0,0, returns 0,0\&. "
.ti -1c
.RI "void \fBNormalize\fP ()"
.br
.ti -1c
.RI "float \fBDot\fP (const Vector2f &rhs) const"
.br
.ti -1c
.RI "float \fBCosineProximity\fP (const Vector2f &rhs) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBDot\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "static float \fBCosineProximity\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "static Vector2f \fBMoveTowards\fP (const Vector2f source, const Vector2f target, const float &maxMagnitude)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const Vector2f \fBZero\fP {0, 0}"
.br
.ti -1c
.RI "static const Vector2f \fBOne\fP {1, 1}"
.br
.ti -1c
.RI "static const Vector2f \fBRight\fP {1, 0}"
.br
.ti -1c
.RI "static const Vector2f \fBLeft\fP {\-1, 0}"
.br
.ti -1c
.RI "static const Vector2f \fBUp\fP {0, 1}"
.br
.ti -1c
.RI "static const Vector2f \fBDown\fP {0, \-1}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "Vector2f \fBoperator+\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f \fBoperator\-\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f \fBoperator*\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f \fBoperator*\fP (Vector2f lhs, const float &rhs)"
.br
.ti -1c
.RI "Vector2f \fBoperator/\fP (Vector2f lhs, const Vector2f &rhs)"
.br
.ti -1c
.RI "Vector2f \fBoperator/\fP (Vector2f lhs, const float &rhs)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Vector2f Mochi::Vector2f::Normalized () const\fR [inline]\fP"

.PP
Returns a new copy of the vector, normlized\&. If vector was 0,0, returns 0,0\&. 
.PP
\fBReturns\fP
.RS 4
The normalized vector\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
