.TH "Mochi::Graphics::FrameData" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::FrameData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBFilename\fP"
.br
.ti -1c
.RI "\fBRectf\fP \fBFrame\fP"
.br
.ti -1c
.RI "\fBRectf\fP \fBSpriteSourceSize\fP"
.br
.ti -1c
.RI "float \fBDuration\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
