.TH "Mochi::Input::IGamepadProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::IGamepadProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Input::DummyGamepadProvider\fP, and \fBMochi::Input::SDLGamepadProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBGamepadData\fP \fBGetData\fP (const unsigned int &player) const =0"
.br
.ti -1c
.RI "virtual bool \fBHasGamepad\fP (const unsigned int &player) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
