.TH "Mochi::Scripting::ScriptingManager" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Scripting::ScriptingManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScriptingManager\fP (\fBFS::PackCatalog\fP *packCatalog)"
.br
.ti -1c
.RI "void \fBExecute\fP (const std::string &code)"
.br
.ti -1c
.RI "void \fBExecuteFile\fP (const std::string &path)"
.br
.ti -1c
.RI "void \fBExecuteGlobal\fP (const std::string &code)"
.br
.ti -1c
.RI "void \fBExecuteFileGlobal\fP (const std::string &path)"
.br
.ti -1c
.RI "void \fBUpdate\fP (const float &dt)"
.br
.ti -1c
.RI "void \fBCleanEnvironment\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sol::state \fBState\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
