.TH "Mochi::Input::InputManager" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::InputManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputManager\fP (std::unique_ptr< \fBIKeyboardProvider\fP > keyboardProvider, std::unique_ptr< \fBIMouseProvider\fP > mouseProvider, std::unique_ptr< \fBIGamepadProvider\fP > mGamepadProvider)"
.br
.ti -1c
.RI "bool \fBIsDown\fP (const int &key) const"
.br
.ti -1c
.RI "bool \fBWasPressed\fP (const int &key) const"
.br
.ti -1c
.RI "bool \fBWasReleased\fP (const int &key) const"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "bool \fBMouseIsDown\fP (const unsigned int &mouseButton) const"
.br
.ti -1c
.RI "bool \fBMouseWasPressed\fP (const unsigned int &mouseButton) const"
.br
.ti -1c
.RI "bool \fBMouseWasReleased\fP (const unsigned int &mouseButton) const"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetMousePosition\fP () const"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetMouseDelta\fP () const"
.br
.ti -1c
.RI "float \fBGetGamepadAxis\fP (const GamepadAxis &axis) const"
.br
.ti -1c
.RI "bool \fBGamepadButtonIsDown\fP (const GamepadButton &button) const"
.br
.ti -1c
.RI "bool \fBGamepadButtonWasPressed\fP (const GamepadButton &button) const"
.br
.ti -1c
.RI "bool \fBGamepadButtonWasReleased\fP (const GamepadButton &button) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
