.TH "Mochi::Event::SDLSystemEventDispatcher" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Event::SDLSystemEventDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Event::ISystemEventDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDLSystemEventDispatcher\fP (\fBEventBus\fP *eventBus)"
.br
.ti -1c
.RI "virtual void \fBPollEvents\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Mochi::Event::SDLSystemEventDispatcher::PollEvents () const\fR [virtual]\fP"

.PP
Implements \fBMochi::Event::ISystemEventDispatcher\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
