.TH "Mochi::Graphics::GUIOptions" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::GUIOptions
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBTexturePath\fP"
.br
.ti -1c
.RI "std::optional< \fBRectf\fP > \fBParentRect\fP"
.br
.ti -1c
.RI "std::optional< \fBRectf\fP > \fBSrcRect\fP"
.br
.ti -1c
.RI "std::optional< \fBRectf\fP > \fBDstRect\fP"
.br
.ti -1c
.RI "std::optional< \fBRectf\fP > \fBSlice\fP"
.br
.ti -1c
.RI "\fBVector2f\fP \fBScreenAnchor\fP"
.br
.ti -1c
.RI "\fBVector2f\fP \fBSpritePivot\fP"
.br
.ti -1c
.RI "std::optional< Color > \fBColor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
