.TH "Mochi::Graphics::DummyTexture" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::DummyTexture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::ITexture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBVector2f\fP \fBGetSize\fP () const override"
.br
.ti -1c
.RI "virtual void \fBSetAlpha\fP (const uint8_t &alpha)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBVector2f\fP Mochi::Graphics::DummyTexture::GetSize () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::ITexture\fP\&.
.SS "virtual void Mochi::Graphics::DummyTexture::SetAlpha (const uint8_t & alpha)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::ITexture\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
