.TH "Mochi::Debug::FrameProfiler" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Debug::FrameProfiler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeginSection\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBEndSection\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBNewFrame\fP ()"
.br
.ti -1c
.RI "std::string \fBReport\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
