.TH "Mochi::Input::IKeyboardProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::IKeyboardProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Input::DummyKeyboardProvider\fP, and \fBMochi::Input::SDLKeyboardProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const bool * \fBGetState\fP () const =0"
.br
.ti -1c
.RI "virtual size_t \fBGetMaxKeys\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
