.TH "Mochi::Graphics::AnimatedSprite" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::AnimatedSprite
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::Spritesheet\fP\&.
.PP
Inherited by \fBMochi::Graphics::OneshotAnimation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimatedSprite\fP (\fBIAnimationFactory\fP *, \fBAbstractTextureFactory\fP *, const std::string &animationPath, const std::string &mainAnimation)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (const float &dt) override"
.br
.ti -1c
.RI "virtual void \fBPlayAnimation\fP (const std::string &animationName)"
.br
.ti -1c
.RI "void \fBStopAnimation\fP ()"
.br
.ti -1c
.RI "std::string \fBGetCurrentAnimation\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBMochi::Graphics::Spritesheet\fP
.in +1c
.ti -1c
.RI "\fBSpritesheet\fP (\fBIAnimationFactory\fP *animationFactory, \fBAbstractTextureFactory\fP *textureFactory, const std::string &animationPath, const int &startingFrame)"
.br
.ti -1c
.RI "void \fBSetFrame\fP (const int &frameIndex)"
.br
.ti -1c
.RI "int \fBGetFrame\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBMochi::Graphics::SpriteBase\fP
.in +1c
.ti -1c
.RI "\fBSpriteBase\fP (\fBAbstractTextureFactory\fP *, const std::string &filename)"
.br
.ti -1c
.RI "void \fBLoadTexture\fP (\fBAbstractTextureFactory\fP *textureFactory, const std::string &filename)"
.br
.ti -1c
.RI "virtual std::vector< \fBRenderCommand\fP > \fBGetRenderData\fP () const"
.br
.ti -1c
.RI "void \fBSetZIndex\fP (const uint16_t &zIndex)"
.br
.ti -1c
.RI "uint16_t \fBGetZIndex\fP () const"
.br
.ti -1c
.RI "bool \fBIsVisible\fP () const"
.br
.ti -1c
.RI "void \fBSetVisible\fP (const bool &visible)"
.br
.ti -1c
.RI "uint8_t \fBGetAlpha\fP () const"
.br
.ti -1c
.RI "void \fBSetAlpha\fP (const uint8_t &alpha)"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBGetTransform\fP () const"
.br
.ti -1c
.RI "void \fBSetTransform\fP (std::shared_ptr< \fBTransform\fP > tr)"
.br
.ti -1c
.RI "void \fBSetSrcRect\fP (const \fBRectf\fP &src)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBmPlaying\fP"
.br
.ti -1c
.RI "float \fBmTimer\fP"
.br
.ti -1c
.RI "int \fBmLoops\fP"
.br
.ti -1c
.RI "bool \fBmForward\fP"
.br
.ti -1c
.RI "std::string \fBmCurrentAnimation\fP"
.br
.in -1c

Protected Attributes inherited from \fBMochi::Graphics::Spritesheet\fP
.in +1c
.ti -1c
.RI "std::shared_ptr< \fBAnimationsData\fP > \fBmAnimationsData\fP"
.br
.in -1c

Protected Attributes inherited from \fBMochi::Graphics::SpriteBase\fP
.in +1c
.ti -1c
.RI "std::shared_ptr< \fBITexture\fP > \fBmTexture\fP"
.br
.ti -1c
.RI "\fBRectf\fP \fBmSrcRect\fP"
.br
.ti -1c
.RI "uint16_t \fBmZindex\fP"
.br
.ti -1c
.RI "bool \fBmVisible\fP"
.br
.ti -1c
.RI "uint8_t \fBmAlpha\fP"
.br
.ti -1c
.RI "\fBVector2f\fP \fBmSize\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBmTransform\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Mochi::Graphics::AnimatedSprite::Update (const float & dt)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBMochi::Graphics::SpriteBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
