.TH "Mochi::Graphics::SDLTexture" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::SDLTexture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::ITexture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDLTexture\fP (SDL_Texture *texture)"
.br
.ti -1c
.RI "virtual \fBVector2f\fP \fBGetSize\fP () const override"
.br
.ti -1c
.RI "SDL_Texture * \fBGetTexture\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetAlpha\fP (const uint8_t &alpha) override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBVector2f\fP Mochi::Graphics::SDLTexture::GetSize () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::ITexture\fP\&.
.SS "void Mochi::Graphics::SDLTexture::SetAlpha (const uint8_t & alpha)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::ITexture\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
