.TH "Mochi::Input::SDLKeyboardProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::SDLKeyboardProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IKeyboardProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const bool * \fBGetState\fP () const override"
.br
.ti -1c
.RI "virtual size_t \fBGetMaxKeys\fP () const override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t Mochi::Input::SDLKeyboardProvider::GetMaxKeys () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IKeyboardProvider\fP\&.
.SS "const bool * Mochi::Input::SDLKeyboardProvider::GetState () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IKeyboardProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
