.TH "Mochi::Graphics::RenderCommand" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::RenderCommand
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBITexture\fP * \fBtexture\fP"
.br
.ti -1c
.RI "\fBRectf\fP \fBsourceRect\fP"
.br
.ti -1c
.RI "\fBRectf\fP \fBdestRect\fP"
.br
.ti -1c
.RI "unsigned int \fBzindex\fP"
.br
.ti -1c
.RI "RenderCommandPositionType \fBPositionType\fP = RenderCommandPositionWorld"
.br
.ti -1c
.RI "std::optional< TiledRenderOptions > \fBTiledRenderOptions\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
