.TH "Mochi::Graphics::Camera" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::Camera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (\fBVector2f\fP startingPosition, float startingZoom, \fBVector2f\fP logicalPresentation)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const float &x, const float &y)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBVector2f\fP &point)"
.br
.ti -1c
.RI "void \fBSetZoom\fP (const float &zoom)"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetPosition\fP () const"
.br
.ti -1c
.RI "float \fBGetZoom\fP () const"
.br
.ti -1c
.RI "void \fBMove\fP (const float &horizontal, const float &vertical)"
.br
.ti -1c
.RI "\fBRectf\fP \fBWorldToScreen\fP (const \fBRectf\fP &dstRect) const"
.br
.ti -1c
.RI "\fBRectf\fP \fBScreenToWorld\fP (const \fBRectf\fP &dstRect) const"
.br
.ti -1c
.RI "\fBVector2f\fP \fBWorldToScreen\fP (const \fBVector2f\fP &position) const"
.br
.ti -1c
.RI "\fBVector2f\fP \fBScreenToWorld\fP (const \fBVector2f\fP &position) const"
.br
.ti -1c
.RI "bool \fBIsOnScreen\fP (const \fBRectf\fP &dstRect) const"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetLogicalPresentation\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
