.TH "Mochi::Input::GamepadData" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::GamepadData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::array< float, GamepadAxis::GAMEPAD_AXIS_COUNT > \fBAxisData\fP"
.br
.ti -1c
.RI "std::array< bool, GamepadButton::GAMEPAD_BUTTON_COUNT > \fBButtonsData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
