.TH "Mochi::Physics::Point" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Physics::Point
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Physics::Shape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP (const \fBVector2f\fP &position)"
.br
.ti -1c
.RI "virtual std::unique_ptr< Shape > \fBClone\fP () const"
.br
.ti -1c
.RI "virtual bool \fBIsColliding\fP (const Shape &other) const override"
.br
.ti -1c
.RI "virtual bool \fBCollides\fP (const Point &p) const override"
.br
.ti -1c
.RI "virtual bool \fBCollides\fP (const \fBLine\fP &l) const override"
.br
.ti -1c
.RI "virtual bool \fBCollides\fP (const \fBCircle\fP &c) const override"
.br
.ti -1c
.RI "virtual bool \fBCollides\fP (const \fBRectangle\fP &r) const override"
.br
.in -1c

Public Member Functions inherited from \fBMochi::Physics::Shape\fP
.in +1c
.ti -1c
.RI "\fBShape\fP (const \fBVector2f\fP &position)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBMochi::Physics::Shape\fP
.in +1c
.ti -1c
.RI "\fBVector2f\fP \fBPosition\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< Shape > Mochi::Physics::Point::Clone () const\fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.
.SS "bool Mochi::Physics::Point::Collides (const \fBCircle\fP & c) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.
.SS "bool Mochi::Physics::Point::Collides (const \fBLine\fP & l) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.
.SS "bool Mochi::Physics::Point::Collides (const Point & p) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.
.SS "bool Mochi::Physics::Point::Collides (const \fBRectangle\fP & r) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.
.SS "bool Mochi::Physics::Point::IsColliding (const Shape & other) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Physics::Shape\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
