.TH "Mochi::Input::DummyMouseProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::DummyMouseProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IMouseProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::array< bool, MouseButton::MouseButtonsCount > \fBGetState\fP (float *x, float *y) const override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual std::array< bool, MouseButton::MouseButtonsCount > Mochi::Input::DummyMouseProvider::GetState (float * x, float * y) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IMouseProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
