.TH "Mochi::Graphics::SDLRenderer" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::SDLRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::IRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDLRenderer\fP (const char *appName, const char *appVersion, const char *appId, const char *windowName)"
.br
.ti -1c
.RI "SDL_Renderer * \fBGetRenderer\fP () const"
.br
.ti -1c
.RI "SDL_Window * \fBGetWindow\fP () const"
.br
.ti -1c
.RI "virtual void \fBStartFrameRendering\fP () const override"
.br
.RI "Initializes a frame\&. "
.ti -1c
.RI "virtual void \fBRender\fP (std::vector< \fBRenderCommand\fP > renderQueue, \fBCamera\fP *camera) const override"
.br
.RI "Actually renders the contents of the render queue projected on the camera\&. "
.ti -1c
.RI "virtual void \fBFinishRendering\fP () const override"
.br
.RI "Finishes a frame rendering\&. "
.ti -1c
.RI "virtual std::unique_ptr< \fBAbstractTextureFactory\fP > \fBCreateTextureFactory\fP (\fBFS::PackCatalog\fP *catalog) const"
.br
.RI "Creates (without ownership) a texture factory of the type compatible with the renderer\&. "
.ti -1c
.RI "virtual std::unique_ptr< \fBAbstractGUI\fP > \fBCreateGUI\fP (\fBFS::PackCatalog\fP *catalog, \fBInput::IActionManager\fP *actionManager)"
.br
.RI "Creates (without ownership) the GUI system compatible with the renderer\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< \fBAbstractGUI\fP > Mochi::Graphics::SDLRenderer::CreateGUI (\fBFS::PackCatalog\fP * catalog, \fBInput::IActionManager\fP * actionManager)\fR [virtual]\fP"

.PP
Creates (without ownership) the GUI system compatible with the renderer\&. 
.PP
\fBParameters\fP
.RS 4
\fIcatalog\fP The file catalog used for the GUI system to load files from\&. 
.br
\fIactionManager\fP The action manager, used to manage UI interactions\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A unique pointer to the created gui system\&. 
.RE
.PP

.PP
Implements \fBMochi::Graphics::IRenderer\fP\&.
.SS "std::unique_ptr< \fBAbstractTextureFactory\fP > Mochi::Graphics::SDLRenderer::CreateTextureFactory (\fBFS::PackCatalog\fP * catalog) const\fR [virtual]\fP"

.PP
Creates (without ownership) a texture factory of the type compatible with the renderer\&. 
.PP
\fBParameters\fP
.RS 4
\fIcatalog\fP The file catalog used for the factory to load files from\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A unique pointer to the created texture factory\&. 
.RE
.PP

.PP
Implements \fBMochi::Graphics::IRenderer\fP\&.
.SS "void Mochi::Graphics::SDLRenderer::FinishRendering () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Finishes a frame rendering\&. 
.PP
Implements \fBMochi::Graphics::IRenderer\fP\&.
.SS "void Mochi::Graphics::SDLRenderer::Render (std::vector< \fBRenderCommand\fP > renderQueue, \fBCamera\fP * camera) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Actually renders the contents of the render queue projected on the camera\&. 
.PP
\fBParameters\fP
.RS 4
\fIrenderQueue\fP The vector of render commands to be drawn\&. 
.br
\fIcamera\fP The camera on which to project the rendering\&. 
.RE
.PP

.PP
Implements \fBMochi::Graphics::IRenderer\fP\&.
.SS "void Mochi::Graphics::SDLRenderer::StartFrameRendering () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Initializes a frame\&. 
.PP
Implements \fBMochi::Graphics::IRenderer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
