.TH "Mochi::Rectf" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Rectf
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectf\fP (float _x=0, float _y=0, float _w=0, float _h=0)"
.br
.ti -1c
.RI "\fBRectf\fP (const Rectf &r)"
.br
.ti -1c
.RI "\fBRectf\fP (Rectf &&r)"
.br
.ti -1c
.RI "\fBRectf\fP (\fBVector2f\fP pos, \fBVector2f\fP size)"
.br
.ti -1c
.RI "\fBRectf\fP (const SDL_FRect &r)"
.br
.ti -1c
.RI "\fBoperator SDL_FRect\fP () const"
.br
.ti -1c
.RI "Rectf & \fBoperator=\fP (const Rectf &other)"
.br
.ti -1c
.RI "Rectf & \fBoperator=\fP (const SDL_FRect &other)"
.br
.ti -1c
.RI "Rectf & \fBoperator+=\fP (const \fBVector2f\fP &rhs)"
.br
.RI "Moves the position of the rect adding a vector\&. "
.ti -1c
.RI "Rectf & \fBoperator\-=\fP (const \fBVector2f\fP &rhs)"
.br
.RI "Moves the position of the rect subtracting a vector\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const Rectf &rhs)"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetPosition\fP () const"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBVector2f\fP &pos)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const float &newX, const float &newY)"
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetSize\fP () const"
.br
.ti -1c
.RI "void \fBSetSize\fP (const \fBVector2f\fP &size)"
.br
.ti -1c
.RI "void \fBSetSize\fP (const float &newW, const float &newH)"
.br
.ti -1c
.RI "void \fBScale\fP (const float &scale)"
.br
.ti -1c
.RI "bool \fBIsTextureValid\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "Rectf \fBoperator+\fP (Rectf lhs, const \fBVector2f\fP &rhs)"
.br
.RI "Moves the position of the rect adding a vector\&. "
.ti -1c
.RI "Rectf \fBoperator\-\fP (Rectf lhs, const \fBVector2f\fP &rhs)"
.br
.RI "Moves the position of the rect subtracting a vector\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const Rectf &lhs, const Rectf &rhs)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Rectf & Mochi::Rectf::operator+= (const \fBVector2f\fP & rhs)\fR [inline]\fP"

.PP
Moves the position of the rect adding a vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP The movement vector 
.RE
.PP
\fBReturns\fP
.RS 4
Modified rect 
.RE
.PP

.SS "Rectf & Mochi::Rectf::operator\-= (const \fBVector2f\fP & rhs)\fR [inline]\fP"

.PP
Moves the position of the rect subtracting a vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP The movement vector 
.RE
.PP
\fBReturns\fP
.RS 4
Modified rect 
.RE
.PP

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "Rectf operator+ (Rectf lhs, const \fBVector2f\fP & rhs)\fR [friend]\fP"

.PP
Moves the position of the rect adding a vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP The movement vector 
.RE
.PP
\fBReturns\fP
.RS 4
Resulting rect 
.RE
.PP

.SS "Rectf operator\- (Rectf lhs, const \fBVector2f\fP & rhs)\fR [friend]\fP"

.PP
Moves the position of the rect subtracting a vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP The movement vector 
.RE
.PP
\fBReturns\fP
.RS 4
Resulting rect 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
