.TH "Mochi::Scripting::ScriptingLayer" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Scripting::ScriptingLayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Layer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInitLayer\fP () override"
.br
.RI "Override this to initialize members and data of your layer when the engine adds this layer to the layer list\&. This is useful if you want to create the layer and delay its inclusion on the engine\&. "
.ti -1c
.RI "virtual bool \fBUpdate\fP (const float &dt) override"
.br
.RI "Override this to give your layer a way to be updated each frame\&. "
.ti -1c
.RI "virtual void \fBRender\fP () const override"
.br
.RI "Override this to send the render commands to the engine\&. This task could be done on the update, but making it here its clearer\&. "
.ti -1c
.RI "virtual void \fBGUI\fP () const override"
.br
.RI "Override this to draw the GUI of your layer\&. Even if this could be done anywhere, doing it here ensure it to be drawn after all rendering is done\&. "
.in -1c

Public Member Functions inherited from \fBMochi::Layer\fP
.in +1c
.ti -1c
.RI "\fBLayer\fP ()"
.br
.RI "Default constructor\&. It initializes with references to the engine subsystems\&. Should only be constructed after the engine is setup\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBMochi::Layer\fP
.in +1c
.ti -1c
.RI "\fBFS::PackCatalog\fP * \fBmCatalog\fP"
.br
.ti -1c
.RI "\fBScripting::ScriptingManager\fP * \fBmScripting\fP"
.br
.ti -1c
.RI "\fBGraphics::Camera\fP * \fBmCamera\fP"
.br
.ti -1c
.RI "\fBEvent::EventBus\fP * \fBmEventBus\fP"
.br
.ti -1c
.RI "\fBGraphics::AbstractGUI\fP * \fBmGUI\fP"
.br
.ti -1c
.RI "\fBInput::IActionManager\fP * \fBmActionManager\fP"
.br
.ti -1c
.RI "\fBAudio::IAudioManager\fP * \fBmAudioManager\fP"
.br
.ti -1c
.RI "\fBGraphics::IRenderer\fP * \fBmRenderer\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Mochi::Scripting::ScriptingLayer::GUI () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Override this to draw the GUI of your layer\&. Even if this could be done anywhere, doing it here ensure it to be drawn after all rendering is done\&. 
.PP
Reimplemented from \fBMochi::Layer\fP\&.
.SS "void Mochi::Scripting::ScriptingLayer::InitLayer ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Override this to initialize members and data of your layer when the engine adds this layer to the layer list\&. This is useful if you want to create the layer and delay its inclusion on the engine\&. 
.PP
Reimplemented from \fBMochi::Layer\fP\&.
.SS "void Mochi::Scripting::ScriptingLayer::Render () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Override this to send the render commands to the engine\&. This task could be done on the update, but making it here its clearer\&. 
.PP
Reimplemented from \fBMochi::Layer\fP\&.
.SS "bool Mochi::Scripting::ScriptingLayer::Update (const float & dt)\fR [override]\fP, \fR [virtual]\fP"

.PP
Override this to give your layer a way to be updated each frame\&. 
.PP
\fBParameters\fP
.RS 4
\fIdt\fP The delta time 
.RE
.PP
\fBReturns\fP
.RS 4
true if the execution should continue, false if the execution should halt\&. 
.RE
.PP

.PP
Reimplemented from \fBMochi::Layer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
