.TH "Mochi::EngineError" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::EngineError
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::runtime_error\&.
.PP
Inherited by \fBMochi::AudioOperationError\fP, \fBMochi::MalformedInputAction\fP, \fBMochi::ResourceNotFoundError\fP, and \fBMochi::SystemInitializationError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEngineError\fP (const std::string &msg, std::source_location loc=std::source_location::current())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
