.TH "Mochi::Graphics::SDLTextureFactory" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::SDLTextureFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::AbstractTextureFactory\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< \fBITexture\fP > \fBLoadTexture\fP (const std::string &texturePath) override"
.br
.RI "Gets a texture from the cache if it exists, or loads it from the catalog if not\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSDLRenderer\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBMochi::Graphics::AbstractTextureFactory\fP
.in +1c
.ti -1c
.RI "std::shared_ptr< \fBITexture\fP > \fBGetTexture\fP (const std::string &texturePath)"
.br
.RI "Gets the texture on the specified path on the file system\&. If the texture is in the cache it returns that one, otherwise it loads the texture from the system\&. "
.ti -1c
.RI "void \fBDeleteCache\fP ()"
.br
.RI "Deletes the texture cache from the factory\&. "
.ti -1c
.RI "void \fBDeleteTexture\fP (const std::string &texturePath)"
.br
.RI "Deletes a single texture from the cache\&. "
.in -1c

Protected Attributes inherited from \fBMochi::Graphics::AbstractTextureFactory\fP
.in +1c
.ti -1c
.RI "std::unordered_map< std::string, std::shared_ptr< \fBITexture\fP > > \fBmTexturesMap\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBITexture\fP > Mochi::Graphics::SDLTextureFactory::LoadTexture (const std::string & texturePath)\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Gets a texture from the cache if it exists, or loads it from the catalog if not\&. 
.PP
\fBParameters\fP
.RS 4
\fItexturePath\fP The texture path in the catalog 
.RE
.PP
\fBReturns\fP
.RS 4
A pointer to the texture 
.RE
.PP

.PP
Implements \fBMochi::Graphics::AbstractTextureFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
