.TH "Mochi::Input::DummyGamepadProvider" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Input::DummyGamepadProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Input::IGamepadProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBGamepadData\fP \fBGetData\fP (const unsigned int &player) const override"
.br
.ti -1c
.RI "virtual bool \fBHasGamepad\fP (const unsigned int &player) const override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBGamepadData\fP Mochi::Input::DummyGamepadProvider::GetData (const unsigned int & player) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IGamepadProvider\fP\&.
.SS "virtual bool Mochi::Input::DummyGamepadProvider::HasGamepad (const unsigned int & player) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Input::IGamepadProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
