.TH "Mochi::Color" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (unsigned int _r, unsigned int _g, unsigned int _b, unsigned int _a)"
.br
.ti -1c
.RI "\fBColor\fP (const Color &c)"
.br
.ti -1c
.RI "\fBColor\fP (Color &&c)"
.br
.ti -1c
.RI "\fBColor\fP (const SDL_Color &c)"
.br
.ti -1c
.RI "\fBoperator SDL_Color\fP () const"
.br
.ti -1c
.RI "Color & \fBoperator=\fP (const Color &other)"
.br
.ti -1c
.RI "Color & \fBoperator=\fP (const SDL_Color &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBr\fP"
.br
.ti -1c
.RI "unsigned int \fBg\fP"
.br
.ti -1c
.RI "unsigned int \fBb\fP"
.br
.ti -1c
.RI "unsigned int \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
