.TH "Mochi::Graphics::FrameTag" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::FrameTag
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "int \fBFrom\fP"
.br
.ti -1c
.RI "int \fBTo\fP"
.br
.ti -1c
.RI "AnimationDirection \fBDirection\fP"
.br
.ti -1c
.RI "int \fBRepeat\fP"
.br
.ti -1c
.RI "std::string \fBUserData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
