.TH "Mochi::Graphics::AbstractTextureFactory" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::AbstractTextureFactory \- This class must be inherited to generate textures of a compatible type with its own renderer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AbstractTextureFactory\&.h>\fP
.PP
Inherited by \fBMochi::Graphics::DummyTextureFactory\fP, and \fBMochi::Graphics::SDLTextureFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBITexture\fP > \fBGetTexture\fP (const std::string &texturePath)"
.br
.RI "Gets the texture on the specified path on the file system\&. If the texture is in the cache it returns that one, otherwise it loads the texture from the system\&. "
.ti -1c
.RI "void \fBDeleteCache\fP ()"
.br
.RI "Deletes the texture cache from the factory\&. "
.ti -1c
.RI "void \fBDeleteTexture\fP (const std::string &texturePath)"
.br
.RI "Deletes a single texture from the cache\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< \fBITexture\fP > \fBLoadTexture\fP (const std::string &texturePath)=0"
.br
.RI "Implement this method to actually load the selected texture from memory onto a format that is compatible with the current renderer\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unordered_map< std::string, std::shared_ptr< \fBITexture\fP > > \fBmTexturesMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class must be inherited to generate textures of a compatible type with its own renderer\&. 

Ownership:

.PP
.IP "\(bu" 2
It maintains a cache of the loaded textures as a map\&.
.IP "\(bu" 2
Clearing the cache is safe anytime, as all the created textures are shared pointers and will only be destroyed when all references are lost\&.
.PP

.PP
Guarantees:

.PP
.IP "\(bu" 2
Valid textures will be only loaded once\&.
.IP "\(bu" 2
Cache will priorize loading from the file system\&.
.IP "\(bu" 2
Deleting a texture or the full cache is safe 
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Mochi::Graphics::AbstractTextureFactory::DeleteCache ()"

.PP
Deletes the texture cache from the factory\&. Clears the textures map, releasing all textures that don't have a reference in any other place\&. Is safe to call whenever\&. 
.SS "void Mochi::Graphics::AbstractTextureFactory::DeleteTexture (const std::string & texturePath)"

.PP
Deletes a single texture from the cache\&. Removes a texture from the cache, releasing it if it doesn't have any reference in any other place\&. Is safe to call whenever\&.

.PP
\fBParameters\fP
.RS 4
\fItexturePath\fP The texture to remove from the cache\&.
.br
\fItexturePath\fP Path to the texture inside the catalog\&. 
.RE
.PP

.SS "std::shared_ptr< \fBITexture\fP > Mochi::Graphics::AbstractTextureFactory::GetTexture (const std::string & texturePath)"

.PP
Gets the texture on the specified path on the file system\&. If the texture is in the cache it returns that one, otherwise it loads the texture from the system\&. 
.PP
\fBParameters\fP
.RS 4
\fItexturePath\fP The path or unique identifier\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A shared pointer to the texture\&. 
.RE
.PP

.SS "virtual std::shared_ptr< \fBITexture\fP > Mochi::Graphics::AbstractTextureFactory::LoadTexture (const std::string & texturePath)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Implement this method to actually load the selected texture from memory onto a format that is compatible with the current renderer\&. 
.PP
\fBParameters\fP
.RS 4
\fItexturePath\fP The path of the texture in the virtual file system\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A shared pointer to the texture\&. 
.RE
.PP

.PP
Implemented in \fBMochi::Graphics::DummyTextureFactory\fP, and \fBMochi::Graphics::SDLTextureFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
