.TH "Mochi::Graphics::DummyGizmos" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::DummyGizmos
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Debug::IGizmos\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDrawRectangle\fP (const \fBPhysics::Rectangle\fP *rectangle, const \fBColor\fP &color) const override"
.br
.ti -1c
.RI "virtual void \fBDrawCircle\fP (const \fBPhysics::Circle\fP *circle, const \fBColor\fP &color) const override"
.br
.ti -1c
.RI "virtual void \fBDrawLine\fP (const \fBPhysics::Line\fP *line, const \fBColor\fP &color) const override"
.br
.ti -1c
.RI "virtual void \fBDrawPoint\fP (const \fBPhysics::Point\fP *point, const \fBColor\fP &color) const override"
.br
.in -1c

Public Member Functions inherited from \fBMochi::Debug::IGizmos\fP
.in +1c
.ti -1c
.RI "void \fBDrawShape\fP (const \fBPhysics::Shape\fP &shape, const \fBColor\fP &color) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Mochi::Graphics::DummyGizmos::DrawCircle (const \fBPhysics::Circle\fP * circle, const \fBColor\fP & color) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Debug::IGizmos\fP\&.
.SS "virtual void Mochi::Graphics::DummyGizmos::DrawLine (const \fBPhysics::Line\fP * line, const \fBColor\fP & color) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Debug::IGizmos\fP\&.
.SS "virtual void Mochi::Graphics::DummyGizmos::DrawPoint (const \fBPhysics::Point\fP * point, const \fBColor\fP & color) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Debug::IGizmos\fP\&.
.SS "virtual void Mochi::Graphics::DummyGizmos::DrawRectangle (const \fBPhysics::Rectangle\fP * rectangle, const \fBColor\fP & color) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Debug::IGizmos\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
