.TH "Mochi::Graphics::GUIResultButton" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::GUIResultButton
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRectf\fP \fBFinalRect\fP"
.br
.ti -1c
.RI "bool \fBFocus\fP"
.br
.ti -1c
.RI "bool \fBPressed\fP"
.br
.ti -1c
.RI "bool \fBReleased\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
