.TH "Mochi::ResourceNotFoundError" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::ResourceNotFoundError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::EngineError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResourceNotFoundError\fP (const std::string &resource, const std::string &hint='')"
.br
.in -1c

Public Member Functions inherited from \fBMochi::EngineError\fP
.in +1c
.ti -1c
.RI "\fBEngineError\fP (const std::string &msg, std::source_location loc=std::source_location::current())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
