.TH "Mochi::Event::ISystemEventDispatcher" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Event::ISystemEventDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMochi::Event::DummyEventDispatcher\fP, and \fBMochi::Event::SDLSystemEventDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPollEvents\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
