.TH "Mochi::Graphics::DummyAnimationFactory" 3 "MochiEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mochi::Graphics::DummyAnimationFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMochi::Graphics::IAnimationFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< \fBAnimationsData\fP > \fBGetAnimationsData\fP (const std::string &animationDataPath) override"
.br
.ti -1c
.RI "virtual void \fBDeleteCache\fP () override"
.br
.ti -1c
.RI "virtual void \fBDeleteAnimation\fP (const std::string &texturePath) override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Mochi::Graphics::DummyAnimationFactory::DeleteAnimation (const std::string & texturePath)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::IAnimationFactory\fP\&.
.SS "virtual void Mochi::Graphics::DummyAnimationFactory::DeleteCache ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::IAnimationFactory\fP\&.
.SS "virtual std::shared_ptr< \fBAnimationsData\fP > Mochi::Graphics::DummyAnimationFactory::GetAnimationsData (const std::string & animationDataPath)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBMochi::Graphics::IAnimationFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MochiEngine from the source code\&.
